version: "3.3"



services:
   nginx:
      image: nginx:stable
      volumes:
         - ./_docker/nginx-back/conf.d/:/etc/nginx/conf.d/
         - ./backend/:/var/www/backend/
         - ./client/:/var/www/client/
      ports:
         - "80:80"
      container_name: app_nginx
      working_dir: /var/www/

   php:
      build:
         context: .
         dockerfile: _docker/php/Dockerfile
      volumes:
         - ./backend/:/var/www/backend/
      container_name: app_php
      depends_on:
         -  mysql

   mysql:
      image: mysql
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: root
      command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
      volumes:
         - ./tmp/mysql/:/var/lib/mysql
         - ./_docker/mysql/init/:/docker-entrypoint-initdb.d
      ports:
         - "3306:3306"
      container_name: app_mysql


   node:
      build:
         context: .
         dockerfile: _docker/node/Dockerfile
      volumes:
         - ./client:/var/www/client/
         - ./client/node_modules:/var/www/client/node_modules
         - ./_docker/node/command.sh:/command.sh
      command: /command.sh
      ports:
         -  3000:3000
      container_name: app_node




